version: '3.8'

services:
  frontend:
    build:
      context: ./UC2-Contactpagina/Showcase-Contactpagina/
      dockerfile: ./Dockerfile
    ports:
      - "7150:7150"
    depends_on:
      - backend

  backend:
    build:
      context: ./UC2-Contactpagina/ShowcaseAPI/
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
